apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: marvelapp-manifests
spec:
  type: git
  params: 
    - name: revision
      value: master
    - name: url
      value: https://github.com/vfiftyfive/CFD12-Demo-Manifests.git